--Eliminacion Tablas
DROP TABLE xtec.CURSO_PROFESOR;
DROP TABLE xtec.CURSO_GRUPO;
DROP TABLE xtec.GRUPO_ESTUDIANTE;
DROP TABLE xtec.CURSO_SEMESTRE;


DROP TABLE xtec.NOTICIA;
DROP TABLE xtec.DOCUMENTO;
DROP TABLE xtec.EVALUACION;
DROP TABLE xtec.ENTREGABLE;

DROP TABLE xtec.GRUPO;
DROP TABLE xtec.RUBRO;
DROP TABLE xtec.CURSO;
DROP TABLE xtec.SEMESTRE;

DROP TABLE xtec.ADMINISTRADOR;
DROP TABLE xtec.ESTUDIANTE;
DROP TABLE xtec.PROFESOR; 